[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.2.4
    bblanchon/ArduinoJson @ ^7.0.4
    4-20ma/ModbusMaster @ ^2.0.1
